name: Test Results

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    
jobs:
  tests:
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
    
      - name: Download test results
        uses: actions/download-artifact@v5.0.0
        with:
          name: junit-results
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - uses: dorny/test-reporter@v3.0.0
        if: always()
        with:
          name: JUnit Results
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit
