name: Test Results

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Download test results
        uses: actions/download-artifact@v5.0.0
        with:
          name: junit-results
          path: .

      - uses: dorny/test-reporter@v3.0.0
        if: always()
        with:
          name: JUnit Results
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit
